name: HimDungeons
version: 0.1-alpha
main: com.him.dungeons.HimDungeons
api-version: 1.20
author: 生电大蛇
description: 专为Paper 26.1.2打造的程序化地牢生成器

depend:
  - WorldEdit

softdepend:
  - Parties
  - Vault
  - Slimefun
  - MythicMobs
  - PlaceholderAPI

commands:
  himdungeons:
    description: HimDungeons 主命令
    usage: /<command> <start|edit|leave|reload>
    aliases: [dungeon, dg]
    permission: himdungeons.start

permissions:
  himdungeons.start:
    description: 允许启动地牢
    default: true
  himdungeons.leave:
    description: 允许离开地牢
    default: true
  himdungeons.admin:
    description: 管理员权限
    default: op
  himdungeons.*:
    default: op
    children:
      himdungeons.start: true
      himdungeons.leave: true
      himdungeons.admin: true